/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2016-01-03 19:24:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class student_002dsign_002dup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005ftoken_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005ftoken_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005ftoken_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <!--Import Google Icon Font-->\r\n");
      out.write("  <link href=\"http://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("  <!--Import materialize.css-->\r\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("\r\n");
      out.write("  <!--Let browser know website is optimized for mobile-->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("\r\n");
      out.write("\t<nav>\r\n");
      out.write("\t\t<div class=\"nav-wrapper white\">\r\n");
      out.write("\t\t  <a href=\"#!\" class=\"brand-logo left\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/pictures/icon.png\"> </a>\r\n");
      out.write("\t\t  <ul class=\"right hide-on-med-and-down\">\r\n");
      out.write("\t\t    <li><a href=\"about.jsp\" class=\"yellow-text text-darken-2\"><i class=\"material-icons left\">info</i>About</a></li>\r\n");
      out.write("\t\t  </ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"pad\">\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"row white center\" id=\"FormBg\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<h4 class=\"col s12 yellow-text text-darken-2\">Student Sign Up</h4>\r\n");
      out.write("\t\t\t\t<form class=\"col s12 \" action=\"signupSubmit\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s6\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"studentNo\" type=\"text\" class=\"validate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${strStudentCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" name=\"student.strStudentCode\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"studentNo\">Student Number</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"file-field input-field col s6\">\r\n");
      out.write("\t\t\t\t\t      <div class=\"btn col s6\">\r\n");
      out.write("\t\t\t\t\t        <span>Upload Picture</span>\r\n");
      out.write("\t\t\t\t\t        <input type=\"file\" accept=\"image/*\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t      <div class=\"file-path-wrapper col s6\">\r\n");
      out.write("\t\t\t\t\t        <input class=\"file-path validate\" type=\"text\" id=\"imagePath\">\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"col s12\">Name</h6>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s4\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"firstName\" type=\"text\" class=\"validate\" name=\"student.name.strFirstName\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"firstName\">First Name</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s4\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"middleName\" type=\"text\" class=\"validate\" name=\"student.name.strMiddleName\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"middleNmame\">Middle Name</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s4\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"lastName\" type=\"text\" class=\"validate\" name=\"student.name.strLastName\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"lastName\">Last Name</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"col s6\">Birthday</h6>\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"col s6\">Gender</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col s6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"date\" class=\"datepicker\" id=\"bday\" name=\"student.birthday\" required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t$('.datepicker').pickadate({\r\n");
      out.write("\t\t\t\t\t\t    selectMonths: true, // Creates a dropdown to control month\r\n");
      out.write("\t\t\t\t\t\t    selectYears: 15 // Creates a dropdown of 15 years to control year\r\n");
      out.write("\t\t\t\t\t\t  });fa\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col s6\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"student.strGender\" type=\"radio\" id=\"male\" value=\"Male\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"male\">Male</label>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"student.strGender\" type=\"radio\" id=\"female\" value=\"Female\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"female\">Female</label>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"col s12\">Address</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s3\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"houseNO\" type=\"text\" class=\"validate\" name=\"student.address.strHouseNo\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"houseNO\">Number</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s3\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"street\" type=\"text\" class=\"validate\" name=\"student.address.strStreet\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"street\">Street</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s3\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"brgy\" type=\"text\" class=\"validate\" name=\"student.address.strBarangay\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"brgy\">Barangay</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s3\">\r\n");
      out.write("\t\t\t\t\t\t<input placeholder=\"(optional)\"id=\"subd\" type=\"text\" class=\"validate\" name=\"student.address.strSubdivision\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"subd\">Subdivision</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s6\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"city\" type=\"text\" class=\"validate\" name=\"student.address.strCity\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"city\">City</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s6\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"province\" type=\"text\" class=\"validate\" name=\"student.address.strProvince\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"province\">Province</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"col s12\">Contact Information</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s6\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"email\" type=\"email\" class=\"validate\" name=\"student.strEmail\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"email\">E-mail Address</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s6\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"contanctNo\" type=\"text\" class=\"validate\" name=\"student.strContactNo\"required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"contanctNo\">Contact No.</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h6 class=\"col s12\">Account Information</h6>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s4\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"username\" type=\"text\" class=\"validate\" name=\"student.account.strUsername\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"username\">Username</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s4\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"password\" type=\"password\" class=\"validate\" name=\"student.account.strPassword\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"password\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-field col s4\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"password\" type=\"password\" class=\"validate\" required>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"password\">Re-type Password</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col s12\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col s12\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col s6\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btn-large waves-effect waves-light red\" href=\"index.jsp\">CANCEL\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons right\">cancel</i>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col s6\">\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn-large waves-effect waves-light\" type=\"submit\" name=\"action\">SUBMIT\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"material-icons right\">done</i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_s_005ftoken_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t body {\r\n");
      out.write("\t\t \tbackground-size: cover;\r\n");
      out.write("\t\t    background-image:url('");
      out.print(request.getContextPath());
      out.write("/pictures/Login2.jpg');\r\n");
      out.write("\t\t    background-repeat: no-repeat;\r\n");
      out.write("\t\t    background-attachment: fixed;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t#FormBg{\r\n");
      out.write("\t\twidth: 80%;\r\n");
      out.write("\t\theight: 1000px;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 10%;\r\n");
      out.write("\t\tright: 10%; \t\r\n");
      out.write("\t\ttop: 20%;\r\n");
      out.write("\t\tbox-shadow: 10px 10px 40px black;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t#pad{\r\n");
      out.write("\t\t\theight: 1200px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("  <!--Import jQuery before materialize.js-->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/materialize.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<footer class=\"page-footer yellow darken-2\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col l6 s12 yellow darken-2\">\r\n");
      out.write("                <h5 class=\"white-text\">Follow us!</h5>\r\n");
      out.write("                <p class=\"grey-text text-lighten-4\">Like, share, learn!</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col l4 offset-l2 s12 yellow darken-2\">\r\n");
      out.write("                <h5 class=\"white-text\">Links</h5>\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li><a class=\"grey-text text-lighten-3\" href=\"#!\">www.facebook.com/LyceumOfAlabang</a></li>\r\n");
      out.write("                  <li><a class=\"grey-text text-lighten-3\" href=\"#!\">www.twitter.com/@lyceumOfAlabang</a></li>\r\n");
      out.write("                  <li><a class=\"grey-text text-lighten-3\" href=\"#!\">www.LyceumofAlabang.edu</a></li>\r\n");
      out.write("                  <li><a class=\"grey-text text-lighten-3\" href=\"#!\">www.instagram.com/@LyceumOfAlabang</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"footer-copyright\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("            (c) 2015 Copyright\r\n");
      out.write("            <a class=\"grey-text text-lighten-4 right\" href=\"#!\">More Links</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("</html>\r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005ftoken_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:token
    org.apache.struts2.views.jsp.ui.TokenTag _jspx_th_s_005ftoken_005f0 = (org.apache.struts2.views.jsp.ui.TokenTag) _005fjspx_005ftagPool_005fs_005ftoken_005fnobody.get(org.apache.struts2.views.jsp.ui.TokenTag.class);
    _jspx_th_s_005ftoken_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005ftoken_005f0.setParent(null);
    int _jspx_eval_s_005ftoken_005f0 = _jspx_th_s_005ftoken_005f0.doStartTag();
    if (_jspx_th_s_005ftoken_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005ftoken_005fnobody.reuse(_jspx_th_s_005ftoken_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005ftoken_005fnobody.reuse(_jspx_th_s_005ftoken_005f0);
    return false;
  }
}
